---
title: "in_class_week_01"
author: "Sean Mussenden"
date: "8/30/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries and settings

```{r}
library(tidyverse)
library(lubridate)
library(janitor)
library(tidycensus)
library(googlesheets4)
library(gargle)

# Define API Key
census_api_key("549950d36c22ff16455fe196bbbd01d63cfbe6cf")

# Define google sheets keys
intro_to_data_journalism_1 <- "10B1-iMyBZkB5EjMRFlbgrxcaBnxVJMkHOo8WK3Og66Y"
intro_to_data_journalism_2 <- "1MnVkk3E2SKDj-s37ctlV7SVKcXQKP_DcvxJ9QuXbXi8"
```

## Authorize Google Sheets 4 in the console
```{r}
## Setup for googlesheets authentication
# In the console, type:
 token_fetch()
# It will authenticate with browser
# Then in the console type
gs4_auth(
 email = gargle::gargle_oauth_email(),
 path = NULL,
 scopes = "https://www.googleapis.com/auth/spreadsheets",
 cache = gargle::gargle_oauth_cache(),
 use_oob = gargle::gargle_oob_default(),
 token = NULL
)
# It will authenticate in browser
# Run this in md to confirm it worked, should give my email address
gs4_user()


```

## Load Data

```{r}
### Read in current data from the New York Times county-by-county COVID tracking from GitHub
# Read in county historical data on Aug 31
#covid_county <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
#write_csv(covid_county, "covid_county_current_08_31_2020.csv") 
# Read in state historical data on Aug 31
#covid_state <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
#write_csv(covid_state, "covid_state_current_08_31_2020.csv") 
# Read in US historical data on Aug 31
#covid_us <- read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us.csv")
#write_csv(covid_us, "covid_us_current_08_31_2020.csv") 
# Read in mask usage data
county_mask_use <- read_csv("https://github.com/nytimes/covid-19-data/raw/master/mask-use/mask-use-by-county.csv")
#######################
#Data Journalism 1 ####
#######################

fips_codes

### Read in stored data pulled from NYT Github on Aug 31
covid_county <- read_csv("covid_county_current_08_31_2020.csv") %>%
  filter(!state %in% c("Northern Mariana Islands","Puerto Rico","Virgin Islands", "Guam")) %>%
  filter(!county %in% c("Unknown")) %>%
  select(fips_code = fips, county, state, date, cases, deaths)

covid_state <- read_csv("covid_state_current_08_31_2020.csv") %>%
  filter(!state %in% c("Northern Mariana Islands","Puerto Rico","Virgin Islands", "Guam"))  %>%
  select(fips_code = fips, state, date, cases, deaths)
  
covid_us <- read_csv("covid_us_current_08_31_2020.csv") %>%
  mutate(location="US") %>%
  select(location, everything())

### Read in population data from census
population_county <- get_acs(geography="county", variables=c("B01001_001"),geometry = FALSE, year=2018) %>%
  clean_names() %>%
  select(fips_code=geoid,
         population=estimate) 

population_state<- get_acs(geography="state", variables=c("B01001_001"),geometry = FALSE, year=2018) %>%
  clean_names() %>%
  select(fips_code=geoid,
         population=estimate) 

population_us <- get_acs(geography="us", variables=c("B01001_001"),geometry = FALSE, year=2018) %>%
  clean_names() %>%
  select(fips_code=geoid,
         population=estimate) 

###Join population data to covid data
covid_county <- covid_county %>%
  left_join(population_county, by=c("fips_code")) %>%
  mutate(population = case_when(county == "New York City" ~ 8398748,
                                county == "Kansas City" ~ 491918,
                                county == "Joplin" ~ 50657,
                                TRUE~population)) %>%
  select(-fips_code) 

covid_state <- covid_state %>%
  left_join(population_state, by=c("fips_code")) %>%
  rename(location = state) %>%
  select(-fips_code) 

covid_us <- covid_us %>%
  mutate(fips_code = "1") %>%
  left_join(population_us, by=c("fips_code")) %>%
  select(-fips_code) 

rm(population_county, population_state, population_us)

# Join state and us data

covid_state_us <- covid_state %>%
  bind_rows(covid_us)

#rm(covid_state, covid_us)

### Dataframe of current cases 
covid_county_current <- covid_county %>%
  filter(date == "2020-08-30") 

covid_state_us_current <- covid_state_us %>%
  filter(date == "2020-08-30")

### Dataframe of cumulative monthly cases per capita as of 30th day of each month

covid_county_monthly_case_rate <- covid_county %>%
  filter(str_detect(date,"2020-03-30|2020-04-30|2020-05-30|2020-06-30|2020-07-30|2020-08-30")) %>%
  mutate(date = paste0("d-",date)) %>%
  mutate(cases_per_1000 = cases/population*1000) %>%
  select(county:date, cases_per_1000) %>%
  pivot_wider(names_from = date, values_from = cases_per_1000) %>%
  mutate_if(is.numeric , replace_na, replace = 0)

### Dataframe of cumulative monthly deaths per capita as of 30th day of each month
covid_county_monthly_death_rate <- covid_county %>%
  filter(str_detect(date,"2020-03-30|2020-04-30|2020-05-30|2020-06-30|2020-07-30|2020-08-30")) %>%
  mutate(date = paste0("d-",date)) %>%
  mutate(deaths_per_1000 = deaths/population*1000) %>%
  select(county:date, deaths_per_1000) %>%
  pivot_wider(names_from = date, values_from = deaths_per_1000) %>%
  mutate_if(is.numeric , replace_na, replace = 0)

# Write sheets
sheet_write(covid_county_current, ss = intro_to_data_journalism_1 , sheet = "covid_county_current")
sheet_write(covid_state_us_current, ss = intro_to_data_journalism_1 , sheet = "covid_state_us_current")
sheet_write(covid_county_monthly_case_rate, ss = intro_to_data_journalism_1 , sheet = "covid_county_monthly_case_rate")
sheet_write(covid_county_monthly_death_rate, ss = intro_to_data_journalism_1 , sheet = "covid_county_monthly_death_rate")

```

```{r}
#######################
#Data Journalism 2 ####
#######################

# Read in covid county data, one row is county data on one date
covid_county <- read_csv("covid_county_current_08_31_2020.csv")

# Read in mask usage data
county_mask_use <- read_csv("https://github.com/nytimes/covid-19-data/raw/master/mask-use/mask-use-by-county.csv") %>%
  clean_names() %>%
  rename(fips_code = countyfp)

### Create a dataframe of all counties by case rate, including cumulative data. 
covid_county <- covid_county %>%
    group_by(state, county) %>%
    arrange(date, .by_group = TRUE) %>%
    mutate(daily_unique_cases = cases - lag(cases, default = first(cases)),
           daily_unique_deaths = deaths - lag(deaths, default = first(deaths))
           ) %>%
    mutate(daily_unique_cases = case_when(date == min(date) ~ cases,
                              TRUE ~ daily_unique_cases),
           daily_unique_deaths = case_when(date == min(date) ~ deaths,
                              TRUE ~ daily_unique_deaths)
           ) %>%
    select(fips_code = fips, county, state, date, daily_unique_cases, daily_unique_deaths, cumulative_cases_to_date = cases, cumulative_deaths_to_date = deaths) %>%
  filter(!state %in% c("Northern Mariana Islands","Puerto Rico","Virgin Islands", "Guam")) %>%
  filter(!county %in% c("Unknown"))

### Clean and bind mask usage
covid_county <- covid_county %>%
  left_join(county_mask_use) %>%
  select(fips_code, county, state, date, everything()) %>%
  mutate_at(c("never", "rarely","sometimes","frequently","always"), ~round(.*100,2)) %>%
  rename_at(c("never", "rarely","sometimes","frequently","always"), funs(paste0(.,"_mask_pct")))

### Read in population and race data from census
county_census_stats <- get_acs(geography = "county", variables = "B02001_002", summary_var = "B01001_001", year = 2018) %>%
  select(geoid = GEOID, white_pop = estimate, total_pop = summary_est) %>%
  mutate(geoid = as.character(geoid)) %>%
  mutate(pop_pct_white = round(white_pop/total_pop*100,2)) %>%
  mutate(pop_pct_nonwhite = 100-pop_pct_white) %>%
  mutate(majority_flag = case_when(pop_pct_white  >= 50 ~ "majority_white",
                                   TRUE~"majority_nonwhite")) %>%
  mutate(nonwhite_pop = total_pop-white_pop) %>%
  select(fips_code = geoid,white_pop, nonwhite_pop, everything())

###Join population data to covid data
covid_county <- covid_county %>%
  left_join(county_census_stats, by=c("fips_code")) %>%
  mutate(total_pop = case_when(county == "New York City" ~ 8398748,
                                county == "Kansas City" ~ 491918,
                                county == "Joplin" ~ 50657,
                                TRUE~total_pop)) %>%
  mutate(sometimes_mask_pct = rarely_mask_pct+sometimes_mask_pct+frequently_mask_pct) %>%
  filter(date >= "2020-07-01") %>%
  mutate(daily_unique_cases = case_when(daily_unique_cases < 0 ~ 0,
                                        TRUE ~ daily_unique_cases)) %>%
  mutate(daily_unique_deaths = case_when(daily_unique_deaths < 0 ~ 0,
                                        TRUE ~ daily_unique_deaths)) %>%
  select(-fips_code, -cumulative_cases_to_date, -cumulative_deaths_to_date, -rarely_mask_pct, -sometimes_mask_pct, -always_mask_pct, -nonwhite_pop, -pop_pct_white, -white_pop, -frequently_mask_pct) #%>%
  #select(state, county, date, daily_unique_cases, daily_unique_deaths, total_pop)
  #mutate_at(is.numeric , replace_na, replace = 0)
  glimpse(covid_county)


         
write_csv(covid_county,"covid_county.csv")


```

```{r}

    

```
