---
title: "JOUR472/772 lab_05 | covid analysis, summarizing and grouping"
author: "Sean Mussenden"
date: "9/28/2020"
output:
  html_document:
    theme: cerulean
    highlight: pygments
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lab overview

This lab serves as an introduction to grouping and summarizing. 

This lab has one **objective** for you to complete, and it will walk you step-by-step through completing that objective.  

The **objectives** is:  Download the zip file linked below to your local computer, add it to your GitHub repo, and work through the data notebook (lab_05_workbook.Rmd) step-by-step, reading the text watching embedded videos and editing it as instructed. When you are finished, push the edited file to GitHub.com, and submit the link on ELMS. 

## How this lab works

First, download [this zip file](https://github.com/smussenden/20_fall_data_journalism/raw/master/labs/lab_05/lab_05_workbook/lab_05_workbook.zip) to your desktop and open it up. [Click the link to download](https://github.com/smussenden/20_fall_data_journalism/raw/master/labs/lab_05/lab_05_workbook/lab_05_workbook.zip).

Then, unpack the zip file.  Drag it into your labs folder in your GitHub repo.  Commit the changes in GitHub desktop and push the changes to your repo on GitHub.com.  

Open the lab_05_workbook.Rmd in R studio, and work through it step-by-step, following the instructions. 

## Lab complete

If you have successfully submitted the link to the edited RMarkdown file in your repository on GitHub.com to the ELMS assignment for this lab, you are done!  
